### ISSUE TITLE
Security Vulnerability: Drone CI

### ISSUE THREAD

**Issue by npease18** [Whyrl35/saltstack#2]
I was looking at your .drone.yml file for an example of using the header and I happened to head over to your drone build [here](https://drone.whyrl.fr/Whyrl35/saltstack/9/2/2). In the console, the secret for X-Drone-Token is published. I'm not sure if this is a security risk but wanted to bring it to your attention. 

Hope this helps

**Comment by npease18** [comment]
For clarification, its under push, webhook. Disabling debug mode should do the trick.

**Comment by Whyrl35** [comment]
Thanks for the message and for the fix, it's a missing debug during the setting...
